FROM ruby:2.5

RUN wget http://download.redis.io/releases/redis-4.0.14.tar.gz && \
        tar zxf redis-4.0.14.tar.gz && \
        cp redis-4.0.14/src/redis-trib.rb /bin && \
        chmod +x /bin/redis-trib.rb && \
        apt-get update && apt-get install -y vim && \
        gem install redis --version 4.0.0
